USE master
GO

IF DB_ID('QLST') IS NOT NULL
BEGIN
    -- Đặt database vào chế độ single-user để ngắt tất cả kết nối
    ALTER DATABASE QLST SET SINGLE_USER WITH ROLLBACK IMMEDIATE

    DROP DATABASE QLST
END
GO
CREATE DATABASE QLST
GO 
USE QLST
GO

-- Tạo bảng PHAN_LOAI
CREATE TABLE PHAN_LOAI (
	Loai NVARCHAR(20) PRIMARY KEY,
	DieuKien MONEY,
	GiaTri MONEY
)

-- Tạo bảng KHACH_HANG
CREATE TABLE KHACH_HANG (
    MaKhachHang INT PRIMARY KEY IDENTITY,
    HoTen NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    DiaChi NVARCHAR(200) NOT NULL,
    NgaySinh DATE NOT NULL,
    SoDienThoai NVARCHAR(20) UNIQUE NOT NULL,
    LoaiKhachHang NVARCHAR(20) NOT NULL DEFAULT N'Thân thiết' FOREIGN KEY REFERENCES PHAN_LOAI(Loai),
	NgayDangKy DATE DEFAULT GETDATE(),
    TienTichLuy MONEY NOT NULL DEFAULT 0
)

-- Tạo bảng DANH_MUC
CREATE TABLE DANH_MUC (
    MaDanhMuc INT PRIMARY KEY IDENTITY,
    TenDanhMuc NVARCHAR(100) NOT NULL,
    DaXoa BIT DEFAULT 0
)

-- Tạo bảng NHA_SAN_XUAT
CREATE TABLE NHA_SAN_XUAT (
	MaNhaSanXuat INT PRIMARY KEY IDENTITY,
    TenNhaSanXuat NVARCHAR(50),
    DaXoa BIT DEFAULT 0
)

-- Tạo bảng SAN_PHAM
CREATE TABLE SAN_PHAM (
    MaSanPham INT PRIMARY KEY IDENTITY,
    TenSanPham NVARCHAR(200) NOT NULL,
    MoTa NVARCHAR(255),
    GiaNiemYet MONEY NOT NULL,
    MaDanhMuc INT NOT NULL FOREIGN KEY REFERENCES DANH_MUC(MaDanhMuc),
	MaNhaSanXuat INT NOT NULL FOREIGN KEY REFERENCES NHA_SAN_XUAT(MaNhaSanXuat),
	SoLuongTonKhoHienTai INT NOT NULL,
    SLSPTD INT NOT NULL,
    DaXoa BIT DEFAULT 0
)

-- Tạo bảng KHUYEN_MAI
CREATE TABLE KHUYEN_MAI (
    MaKhuyenMai INT PRIMARY KEY IDENTITY,
    TenKhuyenMai NVARCHAR(200) NOT NULL,
    LoaiKhuyenMai NVARCHAR(10) CHECK (LoaiKhuyenMai IN ('Flash', 'Combo', 'Member')) NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL
)

-- Tạo bảng CHI_TIET_KHUYEN_MAI
CREATE TABLE CHI_TIET_KHUYEN_MAI_FLASH (
    MaKhuyenMai INT NOT NULL FOREIGN KEY REFERENCES KHUYEN_MAI(MaKhuyenMai),
    MaSanPham INT NOT NULL FOREIGN KEY REFERENCES SAN_PHAM(MaSanPham),
    SoLuongConLai INT NOT NULL,
	GiaTriKhuyenMai FLOAT CHECK (GiaTriKhuyenMai BETWEEN 0 AND 100),
    PRIMARY KEY (MaKhuyenMai, MaSanPham)
)

CREATE TABLE CHI_TIET_KHUYEN_MAI_COMBO (
    MaKhuyenMai INT NOT NULL FOREIGN KEY REFERENCES KHUYEN_MAI(MaKhuyenMai),
    MaSanPham1 INT NOT NULL FOREIGN KEY REFERENCES SAN_PHAM(MaSanPham),
	MaSanPham2 INT NOT NULL FOREIGN KEY REFERENCES SAN_PHAM(MaSanPham),
    SoLuongConLai INT NOT NULL,
	GiaTriKhuyenMai FLOAT CHECK (GiaTriKhuyenMai BETWEEN 0 AND 100),
    PRIMARY KEY (MaKhuyenMai, MaSanPham1, MaSanPham2)
)

CREATE TABLE CHI_TIET_KHUYEN_MAI_MEMBER (
    MaKhuyenMai INT NOT NULL FOREIGN KEY REFERENCES KHUYEN_MAI(MaKhuyenMai),
    MaSanPham INT NOT NULL FOREIGN KEY REFERENCES SAN_PHAM(MaSanPham),
	LoaiKhachHang NVARCHAR(20) FOREIGN KEY REFERENCES PHAN_LOAI(Loai),
    SoLuongConLai INT NOT NULL,
	GiaTriKhuyenMai FLOAT CHECK (GiaTriKhuyenMai BETWEEN 0 AND 100),
    PRIMARY KEY (MaKhuyenMai, MaSanPham, LoaiKhachHang)
)

-- Tạo bảng PHIEU_MUA_SAM
CREATE TABLE PHIEU_MUA_SAM (
    MaPhieuMuaSam INT PRIMARY KEY IDENTITY,
	MaKhachHang INT NULL FOREIGN KEY REFERENCES KHACH_HANG(MaKhachHang), -- NULL nếu là khách hàng vãng lai
    NgayDat DATETIME NOT NULL,
	LaOnline BIT NOT NULL, 
	SuDungPhieu BIT DEFAULT 0
)

-- Tạo bảng CHI_TIET_PHIEU_MUA_SAM
CREATE TABLE CHI_TIET_PHIEU_MUA_SAM (
    MaPhieuMuaSam INT NOT NULL FOREIGN KEY REFERENCES PHIEU_MUA_SAM(MaPhieuMuaSam),
    MaSanPham INT NOT NULL FOREIGN KEY REFERENCES SAN_PHAM(MaSanPham),
    SoLuongDat INT NOT NULL CHECK (SoLuongDat > 0),
	PRIMARY KEY (MaPhieuMuaSam, MaSanPham)
)

-- Tạo bảng PHIEU_MUA_HANG
CREATE TABLE PHIEU_MUA_HANG (
    MaPhieuMuaHang INT PRIMARY KEY IDENTITY,
	MaKhachHang INT NOT NULL FOREIGN KEY REFERENCES KHACH_HANG(MaKhachHang), 
	DaDung BIT DEFAULT 0,
	GiaTri MONEY NOT NULL,
	NgayTao DATETIME NOT NULL,
)

-- Tạo bảng HOA_DON
CREATE TABLE HOA_DON (
	MaHoaDon INT PRIMARY KEY IDENTITY,
    MaPhieuMuaSam INT NOT NULL FOREIGN KEY REFERENCES PHIEU_MUA_SAM(MaPhieuMuaSam),
	PhieuMuaHang INT NULL FOREIGN KEY REFERENCES PHIEU_MUA_HANG(MaPhieuMuaHang),
    TrangThaiThanhToan BIT DEFAULT 0,
	--tổng tiền sau khuyến mãi
    TongTien MONEY NOT NULL,
	ThanhToan MONEY NOT NULL
)

-- Tạo bảng CHI_TIET_HOA_DON
CREATE TABLE CHI_TIET_HOA_DON (
	MaChiTietHoaDon INT PRIMARY KEY IDENTITY,
    MaHoaDon INT NOT NULL FOREIGN KEY REFERENCES HOA_DON(MaHoaDon),
    MaSanPham INT NOT NULL FOREIGN KEY REFERENCES SAN_PHAM(MaSanPham),
	MaKhuyenMai INT FOREIGN KEY REFERENCES KHUYEN_MAI(MaKhuyenMai),
    SoLuong INT NOT NULL,
    GiaBan MONEY NOT NULL,
    GiaSauKhuyenMai MONEY NULL,
	--giá sau khi áp khuyến mãi
)

-- Tạo bảng PHIEU_DAT_HANG 
CREATE TABLE PHIEU_DAT_HANG (
    MaNhaSanXuat INT NOT NULL FOREIGN KEY REFERENCES NHA_SAN_XUAT(MaNhaSanXuat),
    MaSanPham INT NOT NULL FOREIGN KEY REFERENCES SAN_PHAM(MaSanPham),
    SoLuongDat INT NOT NULL CHECK (SoLuongDat > 0),
    NgayDat DATETIME DEFAULT GETDATE(),
    DaNhanHang BIT DEFAULT 0 -- 1: Đã hoàn thành, 0: Chưa hoàn thành
	PRIMARY KEY (MaNhaSanXuat, MaSanPham, NgayDat)
)

-- Tạo bảng PHIEU_NHAN_HANG 
CREATE TABLE PHIEU_NHAN_HANG (
    MaNhaSanXuat INT NOT NULL FOREIGN KEY REFERENCES NHA_SAN_XUAT(MaNhaSanXuat),
    MaSanPham INT NOT NULL FOREIGN KEY REFERENCES SAN_PHAM(MaSanPham),
    NgayNhan DATETIME DEFAULT GETDATE(),
    SoLuongNhan INT DEFAULT 0,
	PRIMARY KEY (MaNhaSanXuat, MaSanPham, NgayNhan)
)

-- Tạo bảng THONG_BAO
CREATE TABLE THONG_BAO (
    MaThongBao INT PRIMARY KEY IDENTITY,
    MaKhachHang INT FOREIGN KEY REFERENCES KHACH_HANG(MaKhachHang),
    ThoiDiem DATETIME DEFAULT GETDATE(),
    NoiDung NVARCHAR(255) NOT NULL,
)

-- Tạo bảng THONG_KE
CREATE TABLE THONG_KE (
    NgayThongKe DATE PRIMARY KEY,
    TongDoanhThu MONEY NOT NULL,
    TongKhachHang INT NOT NULL,
)

CREATE TABLE THONG_KE_SAN_PHAM (
	NgayThongKe DATE,
    MaSanPham INT NOT NULL FOREIGN KEY REFERENCES SAN_PHAM(MaSanPham),
	SoLuongDaBan INT, 
	SoLuongKhachHang INT,
	PRIMARY KEY(NgayThongKe, MaSanPham)
)

--cân nhắc: 
--sử dụng money hay decimal
--các type (khách hàng, km) nên để số hay ghi chữ ra
--thông báo có cần tạo bảng không?
--các biến check (boolean) đặt tên như thế nào?

